"use client"; // Added "use client" directive

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import { SessionContextProvider } from "@/components/SessionContextProvider";
import { usePathname } from "next/navigation"; // Import usePathname
import { Toaster } from 'sonner'; // Import Toaster

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata is not allowed in client components, so it's commented out.
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const isDashboardRoute = pathname.startsWith("/dashboard");

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <SessionContextProvider>
          {!isDashboardRoute && <Navbar />} {/* Render global Navbar only if not on dashboard route */}
          <div className="flex-grow">
            {children}
          </div>
          {!isDashboardRoute && <Footer />} {/* Render global Footer only if not on dashboard route */}
          <Toaster richColors position="top-right" /> {/* Add Toaster here */}
        </SessionContextProvider>
      </body>
    </html>
  );
}