// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ymbiaifjczxawhflbadd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InltYmlhaWZqY3p4YXdoZmxiYWRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3MDU2NzYsImV4cCI6MjA3MzI4MTY3Nn0.iNEh1buR38iTE5a9m-bDW2wZwkpctgKoB2URBiDjS-A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);